# Generated by Django 3.1.5 on 2021-01-18 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='+996111222333', regex='^\\+?1?\\d{9,20}$')])),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('middle_name', models.CharField(max_length=255, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('age', models.CharField(max_length=3, null=True)),
                ('clinic_find', models.CharField(choices=[('MD', 'Media'), ('SN', 'Social_Network'), ('RS', 'RELATIVES'), ('D', 'Doctor'), ('OP', 'Operated_Here'), ('E', 'Else')], max_length=255, verbose_name='Откуда узнали')),
                ('active', models.BooleanField(default=False, verbose_name='is active')),
                ('staff', models.BooleanField(default=False, verbose_name='is staff')),
                ('admin', models.BooleanField(default=False)),
                ('balance', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=21, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format', regex='^\\+?1?\\d{9,20}$')])),
                ('otp', models.CharField(blank=True, max_length=9, null=True)),
                ('count', models.IntegerField(default=0, help_text='Number of otp sent')),
                ('logged', models.BooleanField(default=False, help_text='If otp verification got successful')),
                ('forgot', models.BooleanField(default=False, help_text='only true for forgot password')),
                ('forgot_logged', models.BooleanField(default=False, help_text='Only true if validate otp forgot get successful')),
            ],
            options={
                'verbose_name': 'Активационный код',
                'verbose_name_plural': 'Активационный код',
            },
        ),
    ]
