# Generated by Django 3.1.5 on 2021-01-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opera', models.CharField(choices=[('MD', 'Media'), ('SN', 'Social_Network'), ('RS', 'RELATIVES'), ('D', 'Doctor'), ('OP', 'Operated_Here'), ('E', 'Else')], max_length=255, verbose_name='Виды операции')),
                ('beforeopera', models.FileField(upload_to='', verbose_name='Фото до операции')),
                ('afteropera', models.FileField(upload_to='', verbose_name='Фото после операции')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
            ],
        ),
    ]
