# Generated by Django 3.1.5 on 2021-01-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('mail', models.EmailField(max_length=254, verbose_name='Почта')),
                ('message', models.CharField(max_length=2000, verbose_name='Сообщение')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Вопросы',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото блога')),
                ('name_blog', models.CharField(max_length=100, verbose_name='Название блога')),
                ('blog', models.CharField(max_length=1000, verbose_name='Описание блога')),
                ('url_blog', models.CharField(max_length=200, verbose_name='Ссылка блога')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блог',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('feedback', models.CharField(max_length=2000, verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзыв',
            },
        ),
        migrations.CreateModel(
            name='Online',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=200, verbose_name='Телефон')),
                ('opera', models.CharField(choices=[('PL', 'Подтяжка лица'), ('PV', 'Пластика век'), ('KPG', 'Контурная пластика губ'), ('L', 'Липосакция'), ('PJ', 'Пластика живота'), ('PG', 'Пластика груди'), ('PR', 'Пластика дефектов после огнестрельных ранений'), ('PZ', 'Пластика заячьей губы'), ('PPR', 'Пластика послеоперационных рубцов'), ('PTD', 'Пластика травматических дефектов'), ('PPK', 'Пластика послеожоговых контрактур'), ('PLS', 'Пластика врожденных ложных суставов'), ('PDP', 'Пластика дефектов после удаления опухолей'), ('EGS', 'Эндопротезирование груди силиконовыми имплантами'), ('MSN', 'Микрохирургический шов повреждений нервов верхней конечности'), ('MSS', 'Микрохирургический шов сухожилий кисти'), ('XS', 'Хирургическое лечение болей в  кисти'), ('XKS', 'Хирургическая коррекция деформаций конечностей при ДЦП детей')], max_length=255, verbose_name='Виды операции')),
                ('message', models.CharField(max_length=2000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Онлайн консультация',
                'verbose_name_plural': 'Онлайн консультация',
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opera', models.CharField(choices=[('PL', 'Подтяжка лица'), ('PV', 'Пластика век'), ('KPG', 'Контурная пластика губ'), ('L', 'Липосакция'), ('PJ', 'Пластика живота'), ('PG', 'Пластика груди'), ('PR', 'Пластика дефектов после огнестрельных ранений'), ('PZ', 'Пластика заячьей губы'), ('PPR', 'Пластика послеоперационных рубцов'), ('PTD', 'Пластика травматических дефектов'), ('PPK', 'Пластика послеожоговых контрактур'), ('PLS', 'Пластика врожденных ложных суставов'), ('PDP', 'Пластика дефектов после удаления опухолей'), ('EGS', 'Эндопротезирование груди силиконовыми имплантами'), ('MSN', 'Микрохирургический шов повреждений нервов верхней конечности'), ('MSS', 'Микрохирургический шов сухожилий кисти'), ('XS', 'Хирургическое лечение болей в  кисти'), ('XKS', 'Хирургическая коррекция деформаций конечностей при ДЦП детей')], max_length=255, verbose_name='Виды операции')),
                ('beforeopera', models.ImageField(upload_to='', verbose_name='Фото до операции')),
                ('afteropera', models.ImageField(upload_to='', verbose_name='Фото после операции')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Работы',
                'verbose_name_plural': 'Работы',
            },
        ),
    ]
