# Generated by Django 3.1.5 on 2021-01-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20210119_0711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='works',
            options={'verbose_name': 'Работы', 'verbose_name_plural': 'Работы'},
        ),
        migrations.AlterField(
            model_name='works',
            name='afteropera',
            field=models.ImageField(upload_to='', verbose_name='Фото после операции'),
        ),
        migrations.AlterField(
            model_name='works',
            name='beforeopera',
            field=models.ImageField(upload_to='', verbose_name='Фото до операции'),
        ),
    ]
