# Generated by Django 3.1.5 on 2021-01-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_auto_20210119_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото блога')),
                ('name_blog', models.CharField(max_length=100, verbose_name='Название блога')),
                ('blog', models.CharField(max_length=1000, verbose_name='Описание блога')),
                ('url_blog', models.CharField(max_length=200, verbose_name='Ссылка блога')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блог',
            },
        ),
    ]
