# Generated by Django 3.1.5 on 2021-01-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Online',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=200, verbose_name='Телефон')),
                ('opera', models.CharField(choices=[('PL', 'Подтяжка лица'), ('PV', 'Пластика век'), ('KPG', 'Контурная пластика губ'), ('L', 'Липосакция'), ('PJ', 'Пластика живота'), ('PG', 'Пластика груди'), ('PR', 'Пластика дефектов после огнестрельных ранений'), ('PZ', 'Пластика заячьей губы'), ('PPR', 'Пластика послеоперационных рубцов'), ('PTD', 'Пластика травматических дефектов'), ('PPK', 'Пластика послеожоговых контрактур'), ('PLS', 'Пластика врожденных ложных суставов'), ('PDP', 'Пластика дефектов после удаления опухолей'), ('EGS', 'Эндопротезирование груди силиконовыми имплантами'), ('MSN', 'Микрохирургический шов повреждений нервов верхней конечности'), ('MSS', 'Микрохирургический шов сухожилий кисти'), ('XS', 'Хирургическое лечение болей в  кисти'), ('XKS', 'Хирургическая коррекция деформаций конечностей при ДЦП детей')], max_length=255, verbose_name='Виды операции')),
                ('message', models.CharField(max_length=2000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Онлайн консультация',
                'verbose_name_plural': 'Онлайн консультация',
            },
        ),
    ]
